# --- Server Configuration ---
# Sets the port the Spring Boot application will run on.
# 8080 is a common default for backend servers.
server.port=8081

# --- MongoDB Configuration ---
# This is the connection string for your MongoDB database.
# Replace 'localhost:27017' if your database is hosted elsewhere.
# 'eduflex' is the name of the database that will be created.
spring.data.mongodb.uri=mongodb+srv://ts955337_db_user:Beruigris%4013@cluster0.8lutzus.mongodb.net/eduflex?retryWrites=true&w=majority&appName=Cluster0
